apiVersion: v1
kind: Service
metadata:
  name: {{ include "disaster-relief-platform.fullname" . }}-backend
  labels:
    {{- include "disaster-relief-platform.labels" . | nindent 4 }}
    component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "disaster-relief-platform.selectorLabels" . | nindent 4 }}
    component: backend



