apiVersion: v1
kind: Service
metadata:
  name: {{ include "disaster-relief-platform.fullname" . }}-frontend
  labels:
    {{- include "disaster-relief-platform.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "disaster-relief-platform.selectorLabels" . | nindent 4 }}
    component: frontend



